version: "3"

services:
  reportdesigner:
    build: 
      context: ./reportDesigner
      args:
        - NODE_ENV=development
        - CHOKIDAR_USEPOLLING=1
    command: npm run start
    volumes:
     - ./reportDesigner:/opt/app:consistent
    ports:
      - "5000:80"
      - "33889:33889"
    networks:
      - front-tier
      - back-tier

  pdfgenservice:
    build: 
      context: ./pdfGenService
      args:
        - NODE_ENV=development
    command: npm run start
    volumes:
      - ./pdfgenservice:/opt/app:consistent
    ports:
      - "5001:80"
      - "5858:5858"
      - "9229:9229"
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier: